# Generated by Django 4.0.3 on 2022-04-22 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0010_rename_provider_paid_orderservice_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiate', models.BooleanField(default=False, null=True)),
                ('service_ordered_date', models.DateTimeField(auto_now_add=True)),
                ('service_price', models.IntegerField()),
                ('completed_by_user', models.BooleanField(blank=True, default=False, null=True)),
                ('completed_by_provider', models.BooleanField(blank=True, default=False, null=True)),
                ('user_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('provider_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('ref_code', models.CharField(max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ordered_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCompletedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negotiate', models.BooleanField(default=False, null=True)),
                ('service_ordered_date', models.DateTimeField(auto_now_add=True)),
                ('service_price', models.IntegerField()),
                ('completed_by_user', models.BooleanField(blank=True, default=False, null=True)),
                ('completed_by_provider', models.BooleanField(blank=True, default=False, null=True)),
                ('user_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('provider_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('ref_code', models.CharField(max_length=20)),
                ('ordered_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
