# Generated by Django 4.0.3 on 2022-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercompletedservices',
            name='ordered_service',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='renderedservices',
            name='ordered_service',
            field=models.CharField(max_length=300),
        ),
    ]
