# Generated by Django 4.1.3 on 2023-09-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_profile',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
