# Generated by Django 4.0.3 on 2022-04-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_rename_address_service_address_city_and_more'),
        ('users', '0002_alter_ordercompletedservices_ordered_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercompletedservices',
            name='ordered_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AlterField(
            model_name='renderedservices',
            name='ordered_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
