# Generated by Django 4.0.3 on 2022-04-26 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_ordercompletedservices_ordered_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_a_provider', models.BooleanField(blank=True, default=False, null=True)),
                ('service_completed', models.IntegerField(default=0)),
                ('social_url', models.URLField(blank=True)),
                ('service_url', models.URLField(blank=True)),
                ('drivers_licence_no', models.CharField(max_length=12)),
                ('nin_no', models.IntegerField(max_length=11)),
                ('bank', models.CharField(max_length=300)),
                ('bank_no', models.IntegerField(max_length=11)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
