# Generated by Django 4.1 on 2022-08-20 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorderedservices',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redendered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renderedservices',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redendered_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
