# Generated by Django 4.1 on 2022-08-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_completedorderedservices_admin_renderedservices_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceownerdetails',
            name='use_profile_address',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
