# Generated by Django 4.0.3 on 2022-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nin_no',
            field=models.IntegerField(),
        ),
    ]
