# Generated by Django 4.1 on 2022-09-06 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_serviceownerdetails_use_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(blank=True, help_text='Contact phone number', null=True, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{3}-\\d{4}$')]),
        ),
    ]
