# Generated by Django 4.0.3 on 2022-04-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_bank_no_alter_userprofile_nin_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bank_no',
            new_name='bank_acc_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='bank',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='social_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='Profile/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
