# Generated by Django 4.1 on 2022-09-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
