# Generated by Django 4.0.3 on 2022-04-29 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_rename_bank_no_userprofile_bank_acc_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_acc_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='drivers_licence_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_a_provider',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nin_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='person',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='service_url',
        ),
        migrations.CreateModel(
            name='ServiceOwnerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_a_provider', models.BooleanField(blank=True, default=False, null=True)),
                ('state', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('proof_of_address', models.ImageField(upload_to='AddressProof/')),
                ('identity_proof', models.CharField(choices=[('NIN', 'NIN'), ('DRIVERS LICENSE', 'DRIVERS LICENSE')], max_length=100)),
                ('identity_proof_pic', models.ImageField(upload_to='IdentityProof/')),
                ('identity_proof_no', models.IntegerField()),
                ('bank_name', models.CharField(max_length=300)),
                ('bank_acc_number', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
