# Generated by Django 4.0.3 on 2022-04-29 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_remove_userprofile_bank_acc_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceownerdetails',
            name='is_a_provider',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='service_completed',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_a_provider',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceownerdetails',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
