# Generated by Django 4.0.3 on 2022-05-09 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_remove_serviceownerdetails_is_a_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercompletedservices',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renderedservices',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendered_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
