# Generated by Django 4.0.3 on 2022-04-09 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('SOFT SERVICE', 'SOFT SERVICE'), ('HARD SERVICE', 'HARD SERVICE')], default='New', max_length=100)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('negotiate', models.BooleanField(default=False, null=True)),
                ('max_negotiation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_negotiation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('banned', models.BooleanField(blank=True, default=False, null=True)),
                ('banned_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
