# Generated by Django 4.0.3 on 2022-07-05 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('category_image', models.ImageField(blank=True, upload_to='Cat Image/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='Service/')),
                ('category', models.CharField(blank=True, choices=[('DRY CLEANING', 'DRY CLEANING'), ('SALON', 'SALON'), ('CARPENTARY AND WOOD WORK', 'CARPENTARY AND WOOD WORK')], max_length=200, null=True)),
                ('type', models.CharField(choices=[('SOFT SERVICE', 'SOFT SERVICE'), ('HARD SERVICE', 'HARD SERVICE')], default='New', max_length=100)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('service_completed', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField()),
                ('negotiate', models.BooleanField(default=False, null=True)),
                ('max_negotiation_price', models.IntegerField(blank=True, null=True)),
                ('min_negotiation_price', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('banned', models.BooleanField(blank=True, default=False, null=True)),
                ('banned_date', models.DateTimeField(blank=True, null=True)),
                ('service_state', models.CharField(blank=True, max_length=15, null=True)),
                ('service_city', models.CharField(blank=True, max_length=30, null=True)),
                ('service_address', models.CharField(blank=True, max_length=100, null=True)),
                ('service_url', models.URLField(blank=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_service_price', models.IntegerField()),
                ('order_service_negotiate', models.BooleanField(default=False, null=True)),
                ('order_service_negotiate_price', models.IntegerField(blank=True, null=True)),
                ('order_service_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(blank=True, default=False, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('decline', models.BooleanField(blank=True, default=False, null=True)),
                ('completed_by_user', models.BooleanField(blank=True, default=False, null=True)),
                ('completed_by_provider', models.BooleanField(blank=True, default=False, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('service_admin_price', models.IntegerField(blank=True, default=0)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('ref_code', models.CharField(max_length=20)),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('order_service_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceadmin', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
