# Generated by Django 4.0.3 on 2022-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='banned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
