# Generated by Django 4.0.3 on 2022-04-09 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_alter_service_max_negotiation_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_service_price', models.IntegerField()),
                ('order_service_negotiate', models.BooleanField(default=False, null=True)),
                ('order_service_negotiate_price', models.BooleanField(default=False, null=True)),
                ('order_service_date', models.DateTimeField(auto_now_add=True)),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
