# Generated by Django 4.0.3 on 2022-04-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_orderservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='order_service_negotiate_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
