# Generated by Django 4.0.3 on 2022-04-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_orderservice_order_service_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
