# Generated by Django 4.0.3 on 2022-04-09 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0008_orderservice_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='order_service_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceadmin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='ref_code',
            field=models.CharField(max_length=20),
        ),
    ]
