# Generated by Django 4.0.3 on 2022-04-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_orderservice_order_service_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderservice',
            old_name='provider_paid',
            new_name='paid',
        ),
        migrations.RemoveField(
            model_name='orderservice',
            name='user_paid',
        ),
    ]
