# Generated by Django 4.0.3 on 2022-04-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_rename_provider_paid_orderservice_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='service_admin_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
