# Generated by Django 4.0.3 on 2022-04-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_orderservice_service_admin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
