# Generated by Django 4.0.3 on 2022-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_service_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='address',
            new_name='address_city',
        ),
        migrations.AddField(
            model_name='service',
            name='address_state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
