# Generated by Django 4.0.3 on 2022-04-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_rename_address_service_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
