# Generated by Django 4.0.3 on 2022-04-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_orderservice_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='service',
            name='address_state',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='Service/'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_url',
            field=models.URLField(blank=True),
        ),
    ]
