# Generated by Django 4.0.3 on 2022-04-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_service_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_completed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
