# Generated by Django 4.0.3 on 2022-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_service_service_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('category_image', models.ImageField(blank=True, upload_to='Cat Image/')),
            ],
        ),
    ]
