# Generated by Django 4.0.3 on 2022-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion design', 'fashion design'), ('electrical works', 'electrical works'), ('painting', 'painting')], max_length=200, null=True),
        ),
    ]
