# Generated by Django 4.0.3 on 2022-05-09 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderservice',
            old_name='accepted',
            new_name='decline',
        ),
    ]
