# Generated by Django 4.0.3 on 2022-05-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_rename_accepted_orderservice_decline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderservice',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
