# Generated by Django 4.1.3 on 2023-03-09 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('category_image', models.ImageField(blank=True, upload_to='Cat Image/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='Service/')),
                ('category', models.CharField(blank=True, choices=[('DRY CLEANING', 'DRY CLEANING'), ('SALON', 'SALON'), ('CARPENTARY AND WOOD WORK', 'CARPENTARY AND WOOD WORK')], max_length=200, null=True)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('service_completed', models.IntegerField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('banned', models.BooleanField(blank=True, default=False, null=True)),
                ('banned_date', models.DateTimeField(blank=True, null=True)),
                ('service_state', models.CharField(max_length=15)),
                ('service_city', models.CharField(max_length=30)),
                ('service_address', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_service_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(blank=True, default=False, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('decline', models.BooleanField(blank=True, default=False, null=True)),
                ('completed_by_user', models.BooleanField(blank=True, default=False, null=True)),
                ('completed_by_provider', models.BooleanField(blank=True, default=False, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('ref_code', models.CharField(max_length=20)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_admin', to=settings.AUTH_USER_MODEL)),
                ('order_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
