# Generated by Django 4.1 on 2022-08-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_service_orderservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
