# Generated by Django 4.1 on 2022-08-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_remove_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('PLUMBING', 'PLUMBING'), ('fashion design', 'fashion design'), ('mechanic', 'mechanic')], max_length=200, null=True),
        ),
    ]
