# Generated by Django 4.1 on 2022-08-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('DRY CLEANING', 'DRY CLEANING'), ('SALON', 'SALON'), ('CARPENTARY AND WOOD WORK', 'CARPENTARY AND WOOD WORK')], max_length=200, null=True),
        ),
    ]
